[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXTAUTH_URL = "https://kidigoadminpanel.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
